export const OPEN = 'OPEN'
export const LOAD_RECORD = 'LOAD_RECORD'
export const REMOVE_RECORD = 'REMOVE_RECORD'
export const FILTER = 'FILTER'
export const SAVE_RECORD = 'SAVE_RECORD'
export const ADD_RECORD = 'ADD_RECORD'
