export const propertyTypes = [
  { label: 'Text-field', value: 'textfield' },
  { label: 'Phone', value: 'phone' },
  { label: 'Address', value: 'address' },
  { label: 'Picklist', value: 'picklist' },
  { label: 'Multiselect', value: 'multiselect' },
  { label: 'Lookup', value: 'lookup' },
  { label: 'Checkbox', value: 'checkbox' },
  { label: 'Time', value: 'time' },
  { label: 'Date', value: 'date' },
  { label: 'Percent', value: 'percent' },
  { label: 'Memo', value: 'memo' },
  { label: 'Decimal', value: 'decimal' },
  { label: 'Number', value: 'number' },
  { label: 'Url', value: 'url' },
  { label: 'Email', value: 'email' },
  { label: 'Currency', value: 'currency' },
]

export const propertyItems = [
  { id: 1, unused: false, name: 'esse', label: 'esse', type: 'textfield' },
  { id: 2, unused: false, name: 'deserunt', label: 'deserunt', type: 'phone' },
  { id: 3, unused: false, name: 'cillum', label: 'cillum', type: 'address' },
  { id: 4, unused: false, name: 'elit', label: 'elit', type: 'picklist' },
  {
    id: 5,
    unused: false,
    name: 'reprehenderit',
    label: 'reprehenderit',
    type: 'multiselect',
  },
  { id: 6, unused: false, name: 'dolore', label: 'dolore', type: 'lookup' },
  { id: 7, unused: false, name: 'et', label: 'et', type: 'checkbox' },
  { id: 8, unused: false, name: 'aliqua', label: 'aliqua', type: 'time' },
  { id: 9, unused: false, name: 'ut', label: 'ut', type: 'date' },
  { id: 10, unused: false, name: 'aliquip', label: 'aliquip', type: 'percent' },
  { id: 11, unused: false, name: 'velit', label: 'velit', type: 'memo' },
  { id: 12, unused: false, name: 'culpa', label: 'culpa', type: 'decimal' },
  { id: 13, unused: false, name: 'ullamco', label: 'ullamco', type: 'number' },
  { id: 14, unused: true, name: 'id', label: 'id', type: 'url' },
  {
    id: 15,
    unused: true,
    name: 'voluptate',
    label: 'voluptate',
    type: 'email',
  },
  { id: 16, unused: true, name: 'amet', label: 'amet', type: 'currency' },
]
