export const NEW_USER_FIRST_NAME = 'NEW_USER_FIRST_NAME';
export const NEW_USER_LAST_NAME = 'NEW_USER_LAST_NAME';
export const NEW_USER_HOME_PHONE = 'NEW_USER_HOME_PHONE';
export const NEW_USER_MOBILE_PHONE = 'NEW_USER_MOBILE_PHONE';
export const NEW_USER_WORK_PHONE = 'NEW_USER_WORK_PHONE';
export const NEW_USER_EMAIL = 'NEW_USER_EMAIL';